### ISSUE TITLE
Future of dioxus-helmet

### ISSUE THREAD

**Issue by marc2332** [saicu/dioxus-helmet#2]
Hey!

I am building [Dioxus Community](https://github.com/dioxus-community), a place to develop and maintain projects for Dioxus 🧬. If you can't / don't want to maintain this project anymore (it's ok 😃), would you be interested in handling this project to our organization?  This way, others and myself can continue working on it ! 😃

The idea would be to transfer the repo over GitHub, so the stars, issues & pull request history is preserved! Also the transfer of the [crate](https://crates.io/crates/dioxus-helmet) would be required. I'll leave some credits to you on the README too! ❤️

Let me know what you think, thank you!

**Comment by saicu** [comment]
Hey,
sorry for taking so long for the response.

I would be happy to do so, as I'm not really having the time to maintain this.

**Comment by marc2332** [comment]
Thanks @saicu 😄 🦀
